name: Feature Request
description: Propose a new feature for the app
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please fill out the details below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A short, clear description of the requested feature.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of the App
      description: Which part of the app does this feature relate to?
      multiple: true
      options:
        - Check-in
        - Meals
        - Showers
        - Laundry
        - Bicycle Services
        - Donations
        - Dashboard/Reports
        - Guest Management
        - Settings
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significant impact
        - Critical - Blocking issue
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Quality & Testing Requirements (Mandatory)
        
        **All implementations MUST complete the following:**
        
        - ✅ Read relevant existing code and follow current patterns
        - ✅ Implement complete logic (no placeholders)
        - ✅ Add/update tests for all new logic and UI changes
        - ✅ Run lint: `npm run lint`
        - ✅ Run full tests: `npm test -- --run`
        - ✅ Verify no regressions
        - ✅ Update documentation if applicable
        - ✅ **Update version & changelog** in `src/lib/utils/appVersion.ts`:
          - Bump `APP_VERSION` (use semantic versioning)
          - Add new entry to `CHANGELOG` array with feature details (keep it minimal and non-technical)
        - ✅ Share screenshot of new UI or feature
        
        ## Database Migration Requirements
        
        **If this feature requires database schema changes:**
        
        - ✅ Create migration file in `supabase/migrations/` folder (e.g., `supabase/migrations/20240209120000_add_daily_notes_table.sql`)
        - ✅ Migration files are automatically applied via CI/CD when merged to main
        - ✅ Follow Supabase naming convention: `YYYYMMDDHHMMSS_description.sql` (timestamp + description)
        - ✅ Generate migrations using Supabase CLI locally: `supabase migration new description`
        - ✅ Test migrations locally before pushing: `supabase db reset` then `supabase db push`
        - ✅ Keep `database/schema.sql` updated as a reference (run `supabase db dump` to update)
        
        **Note:** The CI workflow detects changes to the `supabase/migrations/` folder and runs `supabase db push` automatically on merge to main.
        
        **Reference:** [Supabase Database Migrations Documentation](https://supabase.com/docs/guides/deployment/database-migrations)

        ## Feature Removal / Cleanup Requirements

        **If this request removes, replaces, or deprecates an existing feature:**

        - ✅ Remove UI entry points (pages, tabs, nav links, buttons, modals, routes)
        - ✅ Remove or refactor related store/actions/hooks/selectors
        - ✅ Remove obsolete backend/API logic and related permissions/policies
        - ✅ Remove or migrate database artifacts (tables, columns, enums, triggers, views, RLS policies) via migration files
        - ✅ Remove dead utilities/types/constants and unused dependencies/imports
        - ✅ Remove or update tests (unit, integration, component/e2e) for deleted behavior
        - ✅ Verify no orphaned references remain (`grep`/TypeScript/lint should be clean)
        - ✅ Update docs, runbooks, and user-facing guidance to reflect removal
        - ✅ Include migration/backfill/rollback notes if data is being deleted or transformed

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes (Optional)
      description: Any other context, mockups, links, or references.
      placeholder: Add any additional context here...
    validations:
      required: false
