name: Feature Request
description: Propose a new feature for the app
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please fill out the details below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A short, clear description of the requested feature.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of the App
      description: Which part of the app does this feature relate to?
      multiple: true
      options:
        - Check-in
        - Meals
        - Showers
        - Laundry
        - Bicycle Services
        - Donations
        - Dashboard/Reports
        - Guest Management
        - Settings
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significant impact
        - Critical - Blocking issue
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Quality & Testing Requirements (Mandatory)
        
        **All implementations MUST complete the following:**
        
        - ✅ Read relevant existing code and follow current patterns
        - ✅ Implement complete logic (no placeholders)
        - ✅ Add/update tests for all new logic and UI changes
        - ✅ Run lint: `npm run lint`
        - ✅ Run full tests: `npm test -- --run`
        - ✅ Verify no regressions

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes (Optional)
      description: Any other context, mockups, links, or references.
      placeholder: Add any additional context here...
    validations:
      required: false
